on:
  push:
    tags:
      - "*/v*"
      # version tag should be like d1-pac/v1.2.3
  workflow_dispatch:

name: Publish Crate

jobs:
  publish-d1-pac:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/d1-pac')
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Rust targets
        run: rustup target add riscv64imac-unknown-none-elf
      - uses: katyo/publish-crates@v1
        with:
          path: "./d1-pac"
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
